general.import = ["~/.cache/wal/colors-alacritty.toml"]
[font]
size = 12.0

[font.normal]
family = "JetBrainsMonoNLNerdFont"
style = "Regular"

[window]
opacity = 0.7

[window.padding]
x = 15
y = 15

[selection]
save_to_clipboard = true
